app = "investxxx"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8501"

[[services]]
  internal_port = 8501
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 50

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/_stcore/health"

